files: 'advent_of_code\/'
repos:
-   repo: https://github.com/python/black
    rev: 21.12b0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: [--per-file-ignores=__init__.py:F401]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
        language: system
